In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

df = pd.read_csv("accidents.csv")
# df.dtypes
# df.head(10)

features = [
    "Severity",
    "StartLat",
    "StartLng",
    "Distance",
    # "Zipcode",
]

X = df[features]
X.head()

   Severity   StartLat    StartLng  Distance
0         2  34.789009  -82.483383     0.000
1         2  40.998264  -76.650396     0.472
2         3  33.461292 -112.082001     0.000
3         2  42.288445  -87.924911     0.000
4         2  36.229259  -86.594650     0.000

In [10]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled.head()

   Severity  StartLat  StartLng  Distance
0 -0.613776 -0.352381  0.774024 -0.174263
1 -0.613776  0.915880  1.110081  0.111248
2  1.200680 -0.623572 -0.931244 -0.174263
3 -0.613776  1.179404  0.460521 -0.174263
4 -0.613776 -0.058205  0.537161 -0.174263

In [11]:
inertia = []

for k in range(2, 11):
    model = KMeans(
        n_clusters=k,
        random_state=42
    )
    model.fit(X_scaled)
    inertia.append(model.inertia_)

elbow_df = pd.DataFrame({
    "k": range(2, 11),
    "Inertia": inertia
})

fig = px.line(
    elbow_df,
    x="k",
    y="Inertia",
    markers=True,
    title="Elbow Method for Choosing the Number of Clusters"
)

fig.update_layout(
    xaxis_title="Number of Clusters (k)",
    yaxis_title="Inertia",
    template="plotly_white"
)

fig.show()